{{- if .Values.aggregator.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "aparavi.aggregator.fullname" . }}
  labels:
    {{- include "aparavi.aggregator.labels" . | nindent 4 }}
type: Opaque
data:
  mysql-password: {{ .Values.aggregator.config.mysql.password | b64enc | quote }}
{{- end }}
