{{- if .Values.appagent.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "aparavi.appagent.fullname" . }}
  labels:
    {{- include "aparavi.appagent.labels" . | nindent 4 }}
type: Opaque
data:
  mysql-password: {{ .Values.appagent.config.mysql.password | b64enc | quote }}
{{- end }}
