{{- if and .Values.collector.enabled .Values.collector.pvc.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "aparavi.collector.fullname" . -}}-data
  labels:
    {{- include "aparavi.collector.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
  {{ if ne .Values.collector.pvc.storageClassName nil -}}
  storageClassName: {{ .Values.collector.pvc.storageClassName }}
  {{ end -}}
  volumeMode: Filesystem
  {{ if .Values.collector.pvc.volumeName -}}
  volumeName: {{ .Values.collector.pvc.volumeName }}
  {{ end -}}
{{- end }}
