apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "aparavi.collector.fullname" . }}
  labels:
    {{- include "aparavi.collector.labels" . | nindent 4 }}
data:
  config.sh: |
    #!/bin/bash

    tar -xf "${ARTIFACT}"
    export NODE_UUID=$(uuidgen -s -n @x500 -N collector)
    export HOST_UUID=$(uuidgen -s -n @x500 -N collector-host)
    rm "${ARTIFACT}"
    ./node app/webserver.js \
    --moduleType=agent \
    --config.node.nodeName=collector \
    --config.bindTo={{ include "aparavi.aggregator.fullname" . }} \
    --config.node.bindTo={{ include "aparavi.aggregator.fullname" . }} \
    --config.node.nodeId=${NODE_UUID} \
    --config.node.hostId=${HOST_UUID} \
    --enableMetrics=true \
    --no-config.enableHttps \
    --database.extendedObjectInfo=true \
    --config.database.dialect=sqlite \
    --core.startServiceDelay=5 \
    --queue.startServiceDelay=5 \
    --logcon \
    --config.node.parentObjectId=aggregator \
    --debug=ACTN,AUTH,BTCH,CMLD,CMND,CONF,CONS,CORE,CRIT,DATB,DIAG,DNLD,DPRV,ENGI,ERR,ESTK,EVNL,EVNT,FILE,GENR,HTTP,INIT,INST,IPIP,KEYS,KPRV,LIST,LOAD,LOGS,MONI,MSMP,NODC,NODS,NOTF,NPDU,PACK,PARS,PERM,PIPE,PLUG,POLC,POOL,QUEL,QUEP,RLIN,ROOM,ROUT,SBAT,SECR,SESS,SRCH,STOR,TASK,TRAN,TSQL,UPDT,URI \
    --enableErrorStacks
