{{- if .Values.platform.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "aparavi.platform.fullname" . }}
  labels:
    {{- include "aparavi.platform.labels" . | nindent 4 }}
spec:
  {{- if not .Values.platform.autoscaling.enabled }}
  replicas: {{ .Values.platform.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "aparavi.platform.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/platform-configmap.yaml") . | sha256sum }}
        checksum/redisSecret: {{ include (print $.Template.BasePath "/redis-secret.yaml") . | sha256sum }}
        {{- with .Values.platform.podAnnotations }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "aparavi.platform.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "aparavi.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.platform.podSecurityContext | nindent 8 }}
      containers:
        - name: aparavi
          securityContext:
            {{- toYaml .Values.platform.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: {{ include "redis.passwordEnvName" . }}
              {{- include "redis.passwordEnvValue" . | nindent 14 }}
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "aparavi.platform.fullname" . }}
                  key: mysql-password
          ports:
            - name: http
              containerPort: 9452
              protocol: TCP
            - name: net
              containerPort: 9455
              protocol: TCP
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          resources:
            {{- toYaml .Values.platform.resources | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: /root/entrypoint.sh
              subPath: config.sh
      volumes:
      - name: config
        configMap:
          name: {{ include "aparavi.platform.fullname" . }}
          defaultMode: 0100
      {{- with .Values.platform.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.platform.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.platform.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
