apiVersion: v1
kind: Service
metadata:
  name: {{ include "aparavi.fullname" . }}-platform
  labels:
    {{- include "aparavi.labels" . | nindent 4 }}
    component: platform
spec:
  type: {{ .Values.platform.service.type }}
  ports:
    - port: {{ .Values.platform.service.httpPort }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.platform.service.netPort }}
      targetPort: net
      protocol: TCP
      name: net
  selector:
    {{- include "aparavi.selectorLabels" . | nindent 4 }}
    component: platform
