{{- if .Values.platform.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "aparavi.platform.fullname" . }}
  labels:
    {{- include "aparavi.platform.labels" . | nindent 4 }}
data:
  config.sh: |
    #!/bin/bash

    tar -xf "${ARTIFACT}"
    rm "${ARTIFACT}"
    ./node \
      app/webserver.js \
      --config.database.dialect=mysql \
      --config.database.host={{ .Values.mysql.host }} \
      --config.database.password={{ .Values.mysql.password }} \
      --config.database.port={{ .Values.mysql.port }} \
      --config.database.user={{ .Values.mysql.user }} \
      --config.keyStore.dialect=redis \
      --config.keyStore.host={{ .Values.redis.host }} \
      --config.keyStore.password={{ .Values.redis.password }} \
      --config.keyStore.port={{ .Values.redis.port }} \
      --config.node.nodeName=platform \
      --moduleType=platform
{{- end }}
