apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "aparavi.fullname" . }}-platform
  labels:
    {{- include "aparavi.labels" . | nindent 4 }}
    component: platform
spec:
  {{- if not .Values.platform.autoscaling.enabled }}
  replicas: {{ .Values.platform.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "aparavi.selectorLabels" . | nindent 6 }}
      component: platform
  template:
    metadata:
      {{- with .Values.platform.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "aparavi.selectorLabels" . | nindent 8 }}
        component: platform
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "aparavi.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.platform.podSecurityContext | nindent 8 }}
      containers:
        - name: aparavi
          securityContext:
            {{- toYaml .Values.platform.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 9452
              protocol: TCP
            - name: net
              containerPort: 9455
              protocol: TCP
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          resources:
            {{- toYaml .Values.platform.resources | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: /root/entrypoint.sh
              subPath: config.sh
      volumes:
      - name: config
        configMap:
          name: {{ include "aparavi.fullname" . }}-platform
          defaultMode: 0100
      {{- with .Values.platform.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.platform.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.platform.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
