{{- if .Values.platform.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "aparavi.platform.fullname" . }}
  labels:
    {{- include "aparavi.platform.labels" . | nindent 4 }}
data:
  config.sh: |
    #!/bin/bash

    tar -xf "${ARTIFACT}"
    rm "${ARTIFACT}"
    ./node \
      app/webserver.js \
      {{- if .Values.ingress.enabled }}
      --config.baseURL=http{{ if .Values.ingress.tls }}s{{ end }}://{{ get (first .Values.ingress.hosts) "host" }} \
      {{- end }}
      --config.database.dialect=mysql \
      --config.database.host={{ .Values.mysql.host }} \
      --config.database.password={{ .Values.mysql.password }} \
      --config.database.port={{ .Values.mysql.port }} \
      --config.database.user={{ .Values.mysql.user }} \
      --config.keyStore.dialect=redis \
      --config.keyStore.host={{ include "redis.hostname" . }} \
      --config.keyStore.password="${{ include "redis.passwordEnvName" . }}" \
      --config.keyStore.port={{ include "redis.port" . }} \
      --config.node.nodeName=platform \
      --moduleType=platform
{{- end }}
