{{- if .Values.platform.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "aparavi.platform.fullname" . }}
  labels:
    {{- include "aparavi.platform.labels" . | nindent 4 }}
data:
  config.sh: |
    #!/bin/bash

    tar -xf "${ARTIFACT}"
    rm "${ARTIFACT}"
    ./node \
      app/webserver.js \
      --moduleType=platform \
      --root-password="${ROOT_PASSWORD}" \
      --debug=ACTN,AUTH,BTCH,CMLD,CMND,CONF,CONS,CORE,CRIT,DATB,DIAG,DNLD,DPRV,ENGI,ERR,ESTK,EVNL,EVNT,FILE,GENR,HTTP,INIT,INST,IPIP,KEYS,KPRV,LIST,LOAD,LOGS,MONI,MSMP,NODC,NODS,NOTF,NPDU,PACK,PARS,PERM,PIPE,PLUG,POLC,POOL,QUEL,QUEP,RLIN,ROOM,ROUT,SBAT,SECR,SESS,SRCH,STOR,TASK,TRAN,TSQL,UPDT,URI \
      --logcon \
      --enableErrorStacks \
      --config.enableMetrics=true \
      --config.node.nodeId=$(uuidgen -s -n @x500 -N "{{ include "aparavi.platform.fullname" . }}") \
      --config.node.hostId=$(uuidgen -s -n @x500 -N "{{ include "aparavi.platform.fullname" . }}-host") \
      --config.node.nodeName=platform \
      {{- if .Values.ingress.enabled }}
      --config.baseURL=http{{ if .Values.ingress.tls }}s{{ end }}://{{ get (first .Values.ingress.hosts) "host" }} \
      {{- end }}
      --config.database.dialect=mysql \
      --config.database.host={{ include "mysql.hostname" . }} \
      --config.database.port={{ include "mysql.port" . }} \
      --config.database.user={{ .Values.platform.config.mysql.username }} \
      --config.database.password="${MYSQL_PASSWORD}" \
      --config.database.database={{ .Values.platform.config.mysql.database }} \
      --config.keyStore.dialect=redis \
      --config.keyStore.host={{ include "redis.hostname" . }} \
      --config.keyStore.password="${{ include "redis.passwordEnvName" . }}" \
      --config.keyStore.port={{ include "redis.port" . }} \
      --no-config.enableHttps
{{- end }}
